import React from 'react';
import type { DroneSidebarProps } from './DroneSidebar';
import type { DroneHubOverlaysProps } from './DroneHubOverlays';
import type { DroneHubWorkspaceContentProps } from './DroneHubWorkspaceContent';

export function useDroneHubSidebarProps(args: any): DroneSidebarProps {
  const {
    dronesError,
    groupMoveError,
    dronesLoading,
    sidebarDronesFilteredByRepo,
    sidebarDrones,
    sidebarOptimisticDroneIdSet,
    selectedDroneSet,
    selectedIsResponding,
    deletingDrones,
    renamingDrones,
    settingBaseImages,
    movingDroneGroups,
    sidebarGroups,
    collapsedGroups,
    deletingGroups,
    renamingGroups,
    dragOverGroup,
    sidebarHasUngroupedGroup,
    draggingDroneNames,
    dragOverUngrouped,
    repos,
    reposLoading,
    reposError,
    drones,
    droneCountByRepoPath,
    uiDroneName,
    openDraftChatComposer,
    openCreateModal,
    selectDroneCard,
    openCloneModal,
    renameDrone,
    setDroneBaseImage,
    deleteDrone,
    openDroneErrorModal,
    onUngroupedDragOver,
    onUngroupedDragLeave,
    onUngroupedDrop,
    onGroupDragOver,
    onGroupDragLeave,
    onGroupDrop,
    setCollapsedGroups,
    renameGroup,
    setAppView,
    setDraftChat,
    setDraftCreateOpen,
    setDraftCreateError,
    setSelectedGroupMultiChat,
    deleteGroup,
    onDroneDragStart,
    onDroneDragEnd,
    setReposModalOpen,
  } = args;

  return React.useMemo(
    () => ({
      dronesError,
      groupMoveError,
      dronesLoading,
      sidebarDronesFilteredByRepo,
      sidebarDrones,
      sidebarOptimisticDroneIdSet,
      selectedDroneSet,
      selectedIsResponding,
      deletingDrones,
      renamingDrones,
      settingBaseImages,
      movingDroneGroups,
      sidebarGroups,
      collapsedGroups,
      deletingGroups,
      renamingGroups,
      dragOverGroup,
      sidebarHasUngroupedGroup,
      draggingDroneNames,
      dragOverUngrouped,
      repos,
      reposLoading,
      reposError,
      dronesCount: drones.length,
      droneCountByRepoPath,
      uiDroneName,
      onOpenDraftChatComposer: openDraftChatComposer,
      onOpenCreateModal: openCreateModal,
      onSelectDroneCard: selectDroneCard,
      onOpenCloneModal: openCloneModal,
      onRenameDrone: renameDrone,
      onSetDroneBaseImage: (droneId) => {
        void setDroneBaseImage(droneId);
      },
      onDeleteDrone: deleteDrone,
      onOpenDroneErrorModal: openDroneErrorModal,
      onUngroupedDragOver,
      onUngroupedDragLeave,
      onUngroupedDrop,
      onGroupDragOver,
      onGroupDragLeave,
      onGroupDrop,
      onToggleGroupCollapsed: (group) =>
        setCollapsedGroups((prev: Record<string, boolean>) => ({
          ...prev,
          [group]: !prev[group],
        })),
      onRenameGroup: (group) => {
        void renameGroup(group);
      },
      onOpenGroupMultiChat: (group) => {
        setAppView('workspace');
        setDraftChat(null);
        setDraftCreateOpen(false);
        setDraftCreateError(null);
        setSelectedGroupMultiChat(group);
      },
      onDeleteGroup: (group, count) => {
        void deleteGroup(group, count);
      },
      onDroneDragStart,
      onDroneDragEnd,
      onOpenReposModal: () => setReposModalOpen(true),
    }),
    [args],
  );
}

export function useDroneHubOverlaysProps(args: any): DroneHubOverlaysProps {
  const {
    createOpen,
    creating,
    createMode,
    cloneSourceId,
    createNameEntries,
    drones,
    createError,
    createGroup,
    setCreateGroup,
    createRepoPath,
    setCreateRepoPath,
    createRepoMenuEntries,
    createRepoMenuOpen,
    setCreateRepoMenuOpen,
    registeredRepoPaths,
    activeRepoPath,
    cloneIncludeChats,
    setCloneIncludeChats,
    spawnAgentKey,
    setSpawnAgentKey,
    spawnAgentMenuEntries,
    setCustomAgentModalOpen,
    spawnModel,
    setSpawnModel,
    spawnAgentConfig,
    createInitialMessage,
    setCreateInitialMessage,
    createNameRows,
    createMessageSuffixRows,
    createNameCounts,
    appendCreateNameRow,
    updateCreateNameRow,
    updateCreateMessageSuffixRow,
    removeCreateNameRow,
    createNameRef,
    createDrone,
    setCreateOpen,
    draftCreateOpen,
    setDraftCreateOpen,
    draftCreating,
    draftCreateError,
    draftCreateName,
    setDraftCreateName,
    draftCreateNameRef,
    draftNameSuggesting,
    draftSuggestedName,
    draftNameSuggestionError,
    draftCreateGroup,
    setDraftCreateGroup,
    createDroneFromDraft,
    customAgentModalOpen,
    customAgentError,
    customAgents,
    newCustomAgentLabel,
    setNewCustomAgentLabel,
    newCustomAgentCommand,
    setNewCustomAgentCommand,
    setCustomAgents,
    handleAddCustomAgent,
    nameSuggestToast,
    jobsModalError,
    jobsModal,
    builtInAgentOptions,
    spawningAllJobs,
    spawningJobById,
    spawnedJobById,
    spawnJobErrorById,
    detailsOpenByJobId,
    isValidDroneName,
    closeJobsModal,
    spawnAllFromJobsModal,
    spawnOneFromJobsModal,
    spawnJobFromModal,
    onChangeJobsGroup,
    onClearJobsGroup,
    onChangeJobsAgentKey,
    onChangeJobsPrefix,
    onClearJobsPrefix,
    onUpdateJobsModalJob,
    onToggleJobsModalDetails,
    reposModalOpen,
    repos,
    reposError,
    reposLoading,
    deletingRepos,
    setReposModalOpen,
    setActiveRepoPath,
    deleteRepo,
    githubUrlForRepo,
    droneErrorModal,
    clearingDroneError,
    closeDroneErrorModal,
    clearDroneHubError,
    setNameSuggestToast,
  } = args;

  return React.useMemo(
    () => ({
      createDronesModalProps: {
        open: createOpen,
        creating,
        createMode,
        cloneSourceId,
        createNameEntries,
        drones,
        createError,
        createGroup,
        onCreateGroupChange: setCreateGroup,
        onClearCreateGroup: () => setCreateGroup(''),
        createRepoPath,
        onCreateRepoPathChange: setCreateRepoPath,
        onClearCreateRepoPath: () => setCreateRepoPath(''),
        createRepoMenuEntries,
        createRepoMenuOpen,
        onCreateRepoMenuOpenChange: setCreateRepoMenuOpen,
        registeredRepoPaths,
        activeRepoPath,
        cloneIncludeChats,
        onCloneIncludeChatsChange: setCloneIncludeChats,
        spawnAgentKey,
        onSpawnAgentKeyChange: setSpawnAgentKey,
        spawnAgentMenuEntries,
        onOpenCustomAgentModal: () => setCustomAgentModalOpen(true),
        spawnModel,
        onSpawnModelChange: setSpawnModel,
        onClearSpawnModel: () => setSpawnModel(''),
        spawnAgentConfig,
        createInitialMessage,
        onCreateInitialMessageChange: setCreateInitialMessage,
        onClearCreateInitialMessage: () => setCreateInitialMessage(''),
        createNameRows,
        createMessageSuffixRows,
        createNameCounts,
        onAppendCreateNameRow: appendCreateNameRow,
        onUpdateCreateNameRow: updateCreateNameRow,
        onUpdateCreateMessageSuffixRow: updateCreateMessageSuffixRow,
        onRemoveCreateNameRow: removeCreateNameRow,
        createNameRef,
        onSubmitCreate: () => {
          void createDrone();
        },
        onRequestClose: () => {
          setCreateOpen(false);
        },
      },
      draftCreateDroneModalProps: {
        open: draftCreateOpen,
        draftCreating,
        draftCreateError,
        draftCreateName,
        onDraftCreateNameChange: setDraftCreateName,
        draftCreateNameRef,
        draftNameSuggesting,
        draftSuggestedName,
        onUseSuggestedName: () => setDraftCreateName(draftSuggestedName),
        draftNameSuggestionError,
        draftCreateGroup,
        onDraftCreateGroupChange: setDraftCreateGroup,
        onSubmit: () => {
          void createDroneFromDraft();
        },
        onRequestClose: () => setDraftCreateOpen(false),
      },
      customAgentsModalProps: {
        open: customAgentModalOpen,
        customAgentError,
        customAgents,
        newCustomAgentLabel,
        onNewCustomAgentLabelChange: setNewCustomAgentLabel,
        newCustomAgentCommand,
        onNewCustomAgentCommandChange: setNewCustomAgentCommand,
        onDeleteCustomAgent: (id) => setCustomAgents((prev: any[]) => prev.filter((x) => x.id !== id)),
        onAddCustomAgent: handleAddCustomAgent,
        onRequestClose: () => setCustomAgentModalOpen(false),
      },
      hubTransientToastsProps: {
        nameSuggestToast,
        jobsModalError,
        jobsModalOpen: Boolean(jobsModal),
        onDismissNameSuggestToast: () => setNameSuggestToast(null),
      },
      createFromAgentMessageModalProps: {
        jobsModal,
        builtinAgentOptions: builtInAgentOptions,
        customAgents,
        spawningAllJobs,
        spawningJobById,
        spawnedJobById,
        spawnJobErrorById,
        detailsOpenByJobId,
        isValidDroneName,
        onClose: closeJobsModal,
        onSpawnAll: spawnAllFromJobsModal,
        onSpawnOne: spawnOneFromJobsModal,
        onSpawnJob: spawnJobFromModal,
        onOpenCustomAgents: () => setCustomAgentModalOpen(true),
        onChangeGroup: onChangeJobsGroup,
        onClearGroup: onClearJobsGroup,
        onChangeAgentKey: onChangeJobsAgentKey,
        onChangePrefix: onChangeJobsPrefix,
        onClearPrefix: onClearJobsPrefix,
        onUpdateJob: onUpdateJobsModalJob,
        onToggleDetails: onToggleJobsModalDetails,
      },
      reposModalProps: reposModalOpen
        ? {
            repos,
            reposError,
            reposLoading,
            activeRepoPath,
            deletingRepos,
            onClose: () => setReposModalOpen(false),
            onToggleActiveRepoPath: (path) => setActiveRepoPath((prev: string) => (prev === path ? '' : path)),
            onDeleteRepo: (path) => {
              void deleteRepo(path);
            },
            getGithubUrlForRepo: githubUrlForRepo,
          }
        : null,
      droneErrorModalProps: droneErrorModal
        ? {
            droneErrorModal,
            clearingDroneError,
            onClose: closeDroneErrorModal,
            onClearDroneHubError: (droneId) => {
              void clearDroneHubError(droneId);
            },
          }
        : null,
    }),
    [args],
  );
}

export function useDroneHubWorkspaceContentProps(args: any): DroneHubWorkspaceContentProps {
  const {
    appView,
    llmSettingsState,
    hubLogsState,
    hubLogsTailLines,
    hubLogsMaxBytes,
    setAppView,
    onReplayOnboarding,
    onResetOnboarding,
    draftChat,
    nowMs,
    spawnAgentMenuEntries,
    draftCreating,
    draftAutoRenaming,
    spawnAgentConfig,
    createRepoMenuEntries,
    draftCreateError,
    queuedPromptsByDroneChat,
    setDraftChat,
    setDraftCreateOpen,
    setDraftAutoRenaming,
    startDraftPrompt,
    enqueueQueuedPrompt,
    setDraftCreateError,
    selectedGroupMultiChatData,
    groupBroadcastPromptError,
    groupBroadcastSending,
    sendGroupBroadcastPrompt,
    uiDroneName,
    selectDroneCard,
    parseJobsFromAgentMessage,
    dronesLoading,
    sidebarDrones,
    dronesError,
    openDraftChatComposer,
    openCreateModal,
    currentDrone,
    currentDroneLabel,
    showRespondingAsStatusInHeader,
    chatUiMode,
    loadingSession,
    sessionError,
    loadingTranscript,
    transcriptError,
    chatInfoError,
    loadingChatInfo,
    repoOpError,
    repoOpErrorMeta,
    openDroneErrorModal,
    launchHint,
    currentAgentKey,
    pickAgentValue,
    toolbarAgentMenuEntries,
    agentDisabled,
    agentLabel,
    modelControlEnabled,
    availableChatModels,
    currentModel,
    setChatModel,
    setChatInfoError,
    modelMenuEntries,
    modelDisabled,
    modelLabel,
    manualChatModelInput,
    setManualChatModelInput,
    applyManualChatModel,
    setChatModelsRefreshNonce,
    loadingChatModels,
    chatModelsError,
    chatModelsDiscoveredAt,
    chatModelsSource,
    currentDroneRepoAttached,
    currentDroneRepoPath,
    openDroneTerminal,
    openingTerminal,
    openDroneEditor,
    openingEditor,
    pullRepoChanges,
    repoOp,
    headerOverflowRef,
    reseedRepo,
    terminalMenuRef,
    terminalLabel,
    terminalOptions,
    rightPanelOpen,
    setRightPanelOpen,
    setRightPanelSplitMode,
    rightPanelSplit,
    rightPanelTabs,
    rightPanelTab,
    setRightPanelTab,
    rightPanelTabLabels,
    resetRightPanelWidth,
    rightPanelWidthIsDefault,
    transcripts,
    visiblePendingPromptsWithStartup,
    transcriptMessageId,
    parsingJobsByTurn,
    tldrByMessageId,
    showTldrByMessageId,
    toggleTldrForAgentMessage,
    handleAgentMessageHover,
    chatEndRef,
    outputScrollRef,
    updatePinned,
    startupSeedForCurrentDrone,
    sessionText,
    pinnedToBottom,
    selectedDroneIdentity,
    promptError,
    sendingPrompt,
    sendPromptText,
    rightPanelWidth,
    rightPanelWidthMax,
    rightPanelMinWidth,
    rightPanelResizing,
    rightPanelBottomTab,
    setRightPanelBottomTab,
    startRightPanelResize,
    renderRightPanelTabContent,
  } = args;

  return React.useMemo(
    () => ({
      appView,
      settingsViewProps: {
        llm: llmSettingsState,
        hubLogsState,
        hubLogsTailLines,
        hubLogsMaxBytes,
        onBackToWorkspace: () => setAppView('workspace'),
        onReplayOnboarding: () => {
          setAppView('workspace');
          onReplayOnboarding();
        },
        onResetOnboarding,
      },
      draftChatWorkspaceProps: draftChat
        ? {
            draftChat,
            nowMs,
            spawnAgentMenuEntries,
            draftCreating,
            draftAutoRenaming,
            spawnAgentConfig,
            createRepoMenuEntries,
            draftCreateError,
            queuedPromptsByDroneChat,
            onCancel: () => {
              setDraftChat(null);
              setDraftCreateOpen(false);
              setDraftCreateError(null);
              setDraftAutoRenaming(false);
            },
            onStartDraftPrompt: startDraftPrompt,
            onEnqueueQueuedPrompt: enqueueQueuedPrompt,
            onSetDraftCreateError: setDraftCreateError,
          }
        : null,
      groupMultiChatWorkspaceProps: selectedGroupMultiChatData
        ? {
            selectedGroupMultiChatData,
            groupBroadcastPromptError,
            groupBroadcastSending,
            onSendGroupBroadcastPrompt: sendGroupBroadcastPrompt,
            nowMs,
            uiDroneName,
            onSelectDroneCard: selectDroneCard,
            onParseJobsFromAgentMessage: parseJobsFromAgentMessage,
          }
        : null,
      noDroneSelectedStateProps: {
        dronesLoading,
        sidebarDroneCount: sidebarDrones.length,
        dronesError,
        onOpenDraftChatComposer: openDraftChatComposer,
        onOpenCreateModal: openCreateModal,
      },
      selectedDroneWorkspaceProps: currentDrone
        ? {
            currentDrone,
            currentDroneLabel,
            showRespondingAsStatusInHeader,
            chatUiMode,
            loadingSession,
            sessionError,
            loadingTranscript,
            transcriptError,
            chatInfoError,
            loadingChatInfo,
            repoOpError,
            repoOpErrorMeta,
            openDroneErrorModal,
            launchHint,
            currentAgentKey,
            pickAgentValue,
            toolbarAgentMenuEntries,
            agentDisabled,
            agentLabel,
            modelControlEnabled,
            availableChatModels,
            currentModel,
            setChatModel,
            setChatInfoError,
            modelMenuEntries,
            modelDisabled,
            modelLabel,
            manualChatModelInput,
            setManualChatModelInput,
            applyManualChatModel,
            setChatModelsRefreshNonce,
            loadingChatModels,
            chatModelsError,
            chatModelsDiscoveredAt,
            chatModelsSource,
            currentDroneRepoAttached,
            currentDroneRepoPath,
            createRepoMenuEntries,
            openDroneTerminal,
            openingTerminal,
            openDroneEditor,
            openingEditor,
            pullRepoChanges,
            repoOp,
            headerOverflowRef,
            reseedRepo,
            terminalMenuRef,
            terminalLabel,
            terminalOptions,
            rightPanelOpen,
            setRightPanelOpen,
            setRightPanelSplitMode,
            rightPanelSplit,
            rightPanelTabs,
            rightPanelTab,
            setRightPanelTab,
            rightPanelTabLabels,
            resetRightPanelWidth,
            rightPanelWidthIsDefault,
            transcripts,
            visiblePendingPromptsWithStartup,
            transcriptMessageId,
            nowMs,
            parsingJobsByTurn,
            parseJobsFromAgentMessage,
            tldrByMessageId,
            showTldrByMessageId,
            toggleTldrForAgentMessage,
            handleAgentMessageHover,
            chatEndRef,
            outputScrollRef,
            updatePinned,
            startupSeedForCurrentDrone,
            sessionText,
            pinnedToBottom,
            selectedDroneIdentity,
            promptError,
            sendingPrompt,
            sendPromptText,
            rightPanelWidth,
            rightPanelWidthMax,
            rightPanelMinWidth,
            rightPanelResizing,
            rightPanelBottomTab,
            setRightPanelBottomTab,
            startRightPanelResize,
            renderRightPanelTabContent,
          }
        : null,
    }),
    [args],
  );
}
