import type { DroneSidebarProps } from './DroneSidebar';
import type { DroneHubOverlaysProps } from './DroneHubOverlays';
import type { DroneHubWorkspaceContentProps } from './DroneHubWorkspaceContent';

export function useDroneHubSidebarProps(args: any): DroneSidebarProps {
  const {
    dronesError,
    groupMoveError,
    dronesLoading,
    sidebarDronesFilteredByRepo,
    sidebarDrones,
    sidebarOptimisticDroneIdSet,
    selectedDroneSet,
    highlightedDroneIds,
    busyChatNodeIdSet,
    unreadAgentMessageByChatNodeId,
    deletingDrones,
    deleteOperationModeById,
    deleteMode,
    renamingDrones,
    settingBaseImages,
    movingDroneGroups,
    sidebarGroups,
    sidebarGroupCreatedAtByName,
    sidebarHiddenGroupCount,
    collapsedGroups,
    deletingGroups,
    renamingGroups,
    sidebarHasUngroupedGroup,
    repos,
    reposLoading,
    reposError,
    drones,
    droneCountByRepoPath,
    uiDroneName,
    draftSidebarPlaceholder,
    openDraftChatComposer,
    openCreateModal,
    openPlaybookRuns,
    selectDroneCard,
    selectDroneChat,
    createDroneChat,
    renameCanvasChat,
    deleteCanvasChat,
    openCloneModal,
    renameDrone,
    renameDrones,
    setDroneBaseImage,
    deleteDrone,
    reparentDronesToParent,
    openDroneErrorModal,
    moveDronesToGroup,
    createGroup,
    createGroupAndMove,
    setCollapsedGroups,
    renameGroup,
    openGroupMultiChat,
    deleteGroup,
    prepareSidebarDroneDragStart,
    setReposModalOpen,
  } = args;

  return {
    dronesError,
    groupMoveError,
    dronesLoading,
    sidebarDronesFilteredByRepo,
    sidebarDrones,
    sidebarOptimisticDroneIdSet,
    selectedDroneSet,
    highlightedDroneIds,
    busyChatNodeIdSet,
    unreadAgentMessageByChatNodeId,
    deletingDrones,
    deleteOperationModeById,
    deleteMode,
    renamingDrones,
    settingBaseImages,
    movingDroneGroups,
    sidebarGroups,
    sidebarGroupCreatedAtByName,
    sidebarHiddenGroupCount,
    collapsedGroups,
    deletingGroups,
    renamingGroups,
    sidebarHasUngroupedGroup,
    repos,
    reposLoading,
    reposError,
    dronesCount: drones.length,
    droneCountByRepoPath,
    uiDroneName,
    draftSidebarPlaceholder,
    onOpenDraftChatComposer: openDraftChatComposer,
    onOpenCreateModal: openCreateModal,
    onOpenPlaybookRuns: openPlaybookRuns,
    onSelectDroneCard: selectDroneCard,
    onSelectDroneChat: (droneId, chatName) => {
      selectDroneChat(droneId, chatName);
    },
    onCreateDroneChat: async (drone, chatName, opts) =>
      await createDroneChat(drone, chatName, opts),
    onRenameDroneChat: async (droneId, chatName, newName) =>
      await renameCanvasChat(droneId, chatName, newName),
    onDeleteDroneChat: async (droneId, chatName) => await deleteCanvasChat(droneId, chatName),
    onOpenCloneModal: openCloneModal,
    onRenameDrone: renameDrone,
    onRenameDrones: renameDrones,
    onSetDroneBaseImage: (droneId) => {
      void setDroneBaseImage(droneId);
    },
    onDeleteDrone: deleteDrone,
    onOpenDroneErrorModal: openDroneErrorModal,
    onReparentDronesToParent: reparentDronesToParent,
    onMoveDronesToGroup: moveDronesToGroup,
    onCreateGroup: createGroup,
    onCreateGroupAndMove: createGroupAndMove,
    onToggleGroupCollapsed: (group) =>
      setCollapsedGroups((prev: Record<string, boolean>) => ({
        ...prev,
        [group]: !prev[group],
      })),
    onRenameGroup: (group, nextName) => renameGroup(group, nextName),
    onOpenGroupMultiChat: (group) => {
      openGroupMultiChat(group);
    },
    onDeleteGroup: async (group, count, opts) => await deleteGroup(group, count, opts),
    onPrepareDroneDragStart: prepareSidebarDroneDragStart,
    onOpenReposModal: () => setReposModalOpen(true),
  };
}

export function useDroneHubOverlaysProps(args: any): DroneHubOverlaysProps {
  const {
    createOpen,
    creating,
    createMode,
    createRuntime,
    createAsDraft,
    setCreateRuntime,
    setCreateAsDraft,
    createPersistVolume,
    setCreatePersistVolume,
    cloneSourceId,
    createNameEntries,
    drones,
    createError,
    createGroup,
    setCreateGroup,
    createRepoPath,
    setCreateRepoPath,
    createRepoMenuEntries,
    createRepoMenuOpen,
    setCreateRepoMenuOpen,
    registeredRepoPaths,
    activeRepoPath,
    repoBranchSource,
    setRepoBranchSource,
    repoCreateRemoteBranch,
    setRepoCreateRemoteBranch,
    createRepoBranchOptions,
    pullHostBranchBeforeCreate,
    setPullHostBranchBeforeCreate,
    cloneIncludeChats,
    setCloneIncludeChats,
    spawnAgentKey,
    setSpawnAgentKey,
    spawnAgentMenuEntries,
    setCustomAgentModalOpen,
    spawnModel,
    setSpawnModel,
    spawnAgentPermissionMode,
    setSpawnAgentPermissionMode,
    spawnAgentReadOnlySupported,
    spawnAgentConfig,
    createInitialMessage,
    setCreateInitialMessage,
    createNameRows,
    createMessageSuffixRows,
    createNameCounts,
    appendCreateNameRow,
    updateCreateNameRow,
    updateCreateMessageSuffixRow,
    removeCreateNameRow,
    createNameRef,
    createDrone,
    setCreateOpen,
    draftCreateOpen,
    setDraftCreateOpen,
    draftCreating,
    draftCreateError,
    draftCreateName,
    setDraftCreateName,
    draftCreateNameRef,
    draftNameSuggesting,
    draftSuggestedName,
    draftNameSuggestionError,
    draftCreateGroup,
    setDraftCreateGroup,
    createDroneFromDraft,
    customAgentModalOpen,
    customAgentError,
    customAgents,
    newCustomAgentLabel,
    setNewCustomAgentLabel,
    newCustomAgentCommand,
    setNewCustomAgentCommand,
    setCustomAgents,
    handleAddCustomAgent,
    nameSuggestToast,
    jobsModalError,
    jobsModal,
    builtInAgentOptions,
    spawningAllJobs,
    spawningJobById,
    spawnedJobById,
    spawnJobErrorById,
    detailsOpenByJobId,
    isValidDroneName,
    closeJobsModal,
    spawnAllFromJobsModal,
    spawnOneFromJobsModal,
    spawnJobFromModal,
    onChangeJobsGroup,
    onClearJobsGroup,
    onChangeJobsAgentKey,
    onChangeJobsPrefix,
    onClearJobsPrefix,
    onUpdateJobsModalJob,
    onToggleJobsModalDetails,
    dismissJobsModalError,
    reposModalOpen,
    repos,
    reposError,
    reposLoading,
    deletingRepos,
    setReposModalOpen,
    setActiveRepoPath,
    deleteRepo,
    githubUrlForRepo,
    deleteMode,
    dirtyDroneApplyModal,
    closeDirtyDroneApplyModal,
    continueDirtyDroneApply,
    droneDeleteConfirm,
    droneDeleteConfirmError,
    closeDroneDeleteConfirm,
    confirmDroneDelete,
    droneErrorModal,
    clearingDroneError,
    closeDroneErrorModal,
    clearDroneHubError,
    droneDropActionModal,
    closeDroneDropActionModal,
    droppedDroneTarget,
    droppedDroneTargetLabel,
    droppedDroneRows,
    assignDroppedDronesToTarget,
    setNameSuggestToast,
  } = args;

  return {
    createDronesModalProps: {
      open: createOpen,
      creating,
      createMode,
      createRuntime,
      onCreateRuntimeChange: setCreateRuntime,
      createAsDraft,
      onCreateAsDraftChange: setCreateAsDraft,
      createPersistVolume,
      onCreatePersistVolumeChange: setCreatePersistVolume,
      cloneSourceId,
      createNameEntries,
      drones,
      createError,
      createGroup,
      onCreateGroupChange: setCreateGroup,
      onClearCreateGroup: () => setCreateGroup(''),
      createRepoPath,
      onCreateRepoPathChange: setCreateRepoPath,
      onClearCreateRepoPath: () => setCreateRepoPath(''),
      createRepoMenuEntries,
      createRepoMenuOpen,
      onCreateRepoMenuOpenChange: setCreateRepoMenuOpen,
      registeredRepoPaths,
      activeRepoPath,
      repoBranchSource,
      onRepoBranchSourceChange: setRepoBranchSource,
      repoCreateRemoteBranch,
      onRepoCreateRemoteBranchChange: setRepoCreateRemoteBranch,
      createRepoHostBranch: createRepoBranchOptions?.hostBranch ?? null,
      createRepoRemoteBranches: createRepoBranchOptions?.remoteBranches ?? [],
      createRepoBranchesLoading: createRepoBranchOptions?.loading ?? false,
      createRepoBranchesError: createRepoBranchOptions?.error ?? null,
      pullHostBranchBeforeCreate,
      onPullHostBranchBeforeCreateChange: setPullHostBranchBeforeCreate,
      cloneIncludeChats,
      onCloneIncludeChatsChange: setCloneIncludeChats,
      spawnAgentKey,
      onSpawnAgentKeyChange: setSpawnAgentKey,
      spawnAgentMenuEntries,
      onOpenCustomAgentModal: () => setCustomAgentModalOpen(true),
      spawnModel,
      onSpawnModelChange: setSpawnModel,
      onClearSpawnModel: () => setSpawnModel(''),
      spawnAgentPermissionMode,
      onSpawnAgentPermissionModeChange: setSpawnAgentPermissionMode,
      spawnAgentReadOnlySupported,
      spawnAgentConfig,
      createInitialMessage,
      onCreateInitialMessageChange: setCreateInitialMessage,
      onClearCreateInitialMessage: () => setCreateInitialMessage(''),
      createNameRows,
      createMessageSuffixRows,
      createNameCounts,
      onAppendCreateNameRow: appendCreateNameRow,
      onUpdateCreateNameRow: updateCreateNameRow,
      onUpdateCreateMessageSuffixRow: updateCreateMessageSuffixRow,
      onRemoveCreateNameRow: removeCreateNameRow,
      createNameRef,
      onSubmitCreate: (initialMessageOverride?: string) => createDrone(initialMessageOverride),
      onRequestClose: () => {
        setCreateOpen(false);
      },
    },
    draftCreateDroneModalProps: {
      open: draftCreateOpen,
      draftCreating,
      draftCreateError,
      draftCreateName,
      onDraftCreateNameChange: setDraftCreateName,
      draftCreateNameRef,
      draftNameSuggesting,
      draftSuggestedName,
      onUseSuggestedName: () => setDraftCreateName(draftSuggestedName),
      draftNameSuggestionError,
      draftCreateGroup,
      onDraftCreateGroupChange: setDraftCreateGroup,
      onSubmit: () => {
        void createDroneFromDraft();
      },
      onRequestClose: () => setDraftCreateOpen(false),
    },
    customAgentsModalProps: {
      open: customAgentModalOpen,
      customAgentError,
      customAgents,
      newCustomAgentLabel,
      onNewCustomAgentLabelChange: setNewCustomAgentLabel,
      newCustomAgentCommand,
      onNewCustomAgentCommandChange: setNewCustomAgentCommand,
      onDeleteCustomAgent: (id) =>
        setCustomAgents((prev: any[]) => prev.filter((x) => x.id !== id)),
      onAddCustomAgent: handleAddCustomAgent,
      onRequestClose: () => setCustomAgentModalOpen(false),
    },
    hubTransientToastsProps: {
      nameSuggestToast,
      jobsModalError,
      jobsModalOpen: Boolean(jobsModal),
      onDismissNameSuggestToast: () => setNameSuggestToast(null),
      onDismissJobsModalError: dismissJobsModalError,
    },
    createFromAgentMessageModalProps: {
      jobsModal,
      builtinAgentOptions: builtInAgentOptions,
      customAgents,
      spawningAllJobs,
      spawningJobById,
      spawnedJobById,
      spawnJobErrorById,
      detailsOpenByJobId,
      isValidDroneName,
      onClose: closeJobsModal,
      onSpawnAll: spawnAllFromJobsModal,
      onSpawnOne: spawnOneFromJobsModal,
      onSpawnJob: spawnJobFromModal,
      onOpenCustomAgents: () => setCustomAgentModalOpen(true),
      onChangeGroup: onChangeJobsGroup,
      onClearGroup: onClearJobsGroup,
      onChangeAgentKey: onChangeJobsAgentKey,
      onChangePrefix: onChangeJobsPrefix,
      onClearPrefix: onClearJobsPrefix,
      onUpdateJob: onUpdateJobsModalJob,
      onToggleDetails: onToggleJobsModalDetails,
    },
    reposModalProps: reposModalOpen
      ? {
          repos,
          reposError,
          reposLoading,
          activeRepoPath,
          deletingRepos,
          onClose: () => setReposModalOpen(false),
          onToggleActiveRepoPath: (path) =>
            setActiveRepoPath((prev: string) => (prev === path ? '' : path)),
          onDeleteRepo: (path) => {
            void deleteRepo(path);
          },
          getGithubUrlForRepo: githubUrlForRepo,
        }
      : null,
    dirtyDroneApplyModalProps: dirtyDroneApplyModal
      ? {
          dirtyDroneApplyModal,
          onCancel: closeDirtyDroneApplyModal,
          onKeepDirtyAndApply: () => {
            void continueDirtyDroneApply('keep');
          },
          onCommitAndApply: () => {
            void continueDirtyDroneApply('commit');
          },
        }
      : null,
    droneDeleteConfirmModalProps:
      droneDeleteConfirm &&
      Array.isArray(droneDeleteConfirm.drones) &&
      droneDeleteConfirm.drones.length > 0
        ? {
            busy: false,
            deleteMode,
            drones: droneDeleteConfirm.drones,
            error: droneDeleteConfirmError,
            onCancel: closeDroneDeleteConfirm,
            onConfirm: () => {
              void confirmDroneDelete();
            },
          }
        : null,
    droneErrorModalProps: droneErrorModal
      ? {
          droneErrorModal,
          clearingDroneError,
          onClose: closeDroneErrorModal,
          onClearDroneHubError: (droneId) => {
            void clearDroneHubError(droneId);
          },
        }
      : null,
    droneDropActionModalProps:
      droneDropActionModal && droppedDroneTarget && droppedDroneRows.length > 0
        ? {
            targetDroneLabel: droppedDroneTargetLabel || droppedDroneTarget.id,
            droppedDrones: droppedDroneRows,
            onAssignAll: assignDroppedDronesToTarget,
            onRequestClose: closeDroneDropActionModal,
          }
        : null,
  };
}

export function useDroneHubWorkspaceContentProps(args: any): DroneHubWorkspaceContentProps {
  const {
    appView,
    setupStatusState,
    llmSettingsState,
    deleteActionSettingsState,
    requestJson,
    hubLogsState,
    hubLogsTailLines,
    hubLogsMaxBytes,
    setAppView,
    setSettingsActiveTab,
    onReplayOnboarding,
    onResetOnboarding,
    draftChat,
    activeRepoPath,
    settingsActiveTab,
    settingsPlaybookFocusId,
    playbookRunsOpen,
    createRuntime,
    createAsDraft,
    createPersistVolume,
    pullHostBranchBeforeCreate,
    repoBranchSource,
    setRepoBranchSource,
    repoCreateRemoteBranch,
    setRepoCreateRemoteBranch,
    setCreateRuntime,
    setCreateAsDraft,
    setCreatePersistVolume,
    draftCreateMode,
    setDraftCreateMode,
    spawnAgentMenuEntries,
    draftCreating,
    draftAutoRenaming,
    spawnAgentConfig,
    createRepoMenuEntries,
    draftCreateRepoPath,
    draftRepoBranchOptions,
    setCustomAgentModalOpen,
    draftCreateName,
    draftCreateGroup,
    draftCreateParentDroneId,
    draftCreateError,
    queuedPromptsByDroneChat,
    setDraftChat,
    setDraftCreateOpen,
    setDraftCreateName,
    setDraftCreateGroup,
    setDraftCreateParentDroneId,
    setDraftAutoRenaming,
    startDraftPrompt,
    startDraftAutomation,
    queueDraftPromptDuringCreate,
    enqueueQueuedPrompt,
    removeQueuedPrompt,
    setDraftCreateError,
    createDroneFromDraft,
    registeredRepoPaths,
    registryGroupNames,
    setActiveRepoPath,
    setSettingsPlaybookFocusId,
    selectedGroupMultiChatData,
    groupBroadcastPromptError,
    groupBroadcastSending,
    sendGroupBroadcastPrompt,
    handleAutoRenameChatFromFirstPrompt,
    publishSelectedDraft,
    publishingDraft,
    uiDroneName,
    drones,
    selectDroneCard,
    selectDroneChat,
    deleteDrone,
    deletingDrones,
    optimisticallyDeletedDrones,
    parseJobsFromAgentMessage,
    spawnDroneHubTaskFromAgentMessage,
    dronesLoading,
    sidebarDrones,
    dronesError,
    unreadAgentMessageByChatNodeId,
    openDraftChatComposer,
    openCreateModal,
    openPlaybookRuns,
    openPlaybookRunArtifact,
    currentDrone,
    deleteMode,
    currentDroneLabel,
    showRespondingAsStatusInHeader,
    chatUiMode,
    loadingSession,
    sessionError,
    loadingTranscript,
    transcriptError,
    chatInfoError,
    loadingChatInfo,
    repoOpError,
    repoOpErrorMeta,
    openDroneErrorModal,
    launchHint,
    currentAgentKey,
    pickAgentValue,
    toolbarAgentMenuEntries,
    agentLocked,
    agentDisabled,
    agentLabel,
    chatRuntimeMetadataAvailable,
    modelControlEnabled,
    availableChatModels,
    currentModel,
    setChatModel,
    agentPermissionMode,
    setChatAgentPermissionMode,
    agentMessageAutoContinueEnabled,
    setAgentMessageAutoContinueEnabled,
    agentSuggestionEnabled,
    setAgentSuggestionEnabled,
    dockerSnapshotAfterAgentMessageEnabled,
    setDockerSnapshotAfterAgentMessageEnabled,
    setChatInfoError,
    modelMenuEntries,
    modelDisabled,
    modelLabel,
    manualChatModelInput,
    setManualChatModelInput,
    applyManualChatModel,
    setChatModelsRefreshNonce,
    loadingChatModels,
    chatModelsError,
    chatModelsDiscoveredAt,
    chatModelsSource,
    currentDroneRepoAttached,
    currentDroneRepoPath,
    openDroneTerminal,
    openingTerminal,
    openDroneEditor,
    openingEditor,
    pullRepoChanges,
    pushRepoChanges,
    repoTransferPeers,
    pullRepoChangesFromDrone,
    applyRepoChangesToDrone,
    openDroneDropActionModal,
    repoOp,
    headerOverflowRef,
    reseedRepo,
    terminalMenuRef,
    terminalLabel,
    terminalOptions,
    rightPanelOpen,
    setRightPanelOpen,
    requestRightPanelTab,
    rightPanelSplit,
    rightPanelTabs,
    rightPanelTab,
    setRightPanelTab,
    rightPanelTabLabels,
    transcripts,
    visiblePendingPromptsWithStartup,
    transcriptMessageId,
    parsingJobsByTurn,
    tldrByMessageId,
    showTldrByMessageId,
    toggleTldrForAgentMessage,
    handleAgentMessageHover,
    latestAgentSuggestionTarget,
    latestAgentSuggestionState,
    requestAgentSuggestionForMessage,
    chatEndRef,
    outputScrollRef,
    updatePinned,
    startupSeedForCurrentDrone,
    sessionText,
    pinnedToBottom,
    selectedDroneIdentity,
    promptError,
    sendingPrompt,
    sendPromptText,
    canStopResponse,
    requestStopResponse,
    stoppingResponse,
    stopResponseError,
    requestCancelPendingPrompt,
    cancellingPendingPromptById,
    cancelPendingPromptErrorById,
    openedEditorFileOpenFailureMessage,
    openedEditorFileOpenFailureAt,
    onOpenMarkdownFileReference,
    rightPanelBottomTab,
    rightPanelOpenRequestSeq,
    renderRightPanelTabContent,
    renderPersistentPreviewContent,
    setPlaybookRunsOpen,
  } = args;

  return {
    appView,
    setupWelcomeProps: setupStatusState.setupStatus?.shouldShowWelcome
      ? {
          setupStatus: setupStatusState.setupStatus,
          setupStatusLoading: setupStatusState.setupStatusLoading,
          setupStatusError: setupStatusState.setupStatusError,
          dismissingWelcome: setupStatusState.dismissingWelcome,
          onDismissWelcome: () => {
            void setupStatusState.dismissWelcome();
          },
          onReload: () => {
            void setupStatusState.reloadSetupStatus();
          },
          onOpenProfiles: () => {
            setSettingsActiveTab('profiles');
            setAppView('settings');
          },
          onOpenGeneralSettings: () => {
            setSettingsActiveTab('general');
            setAppView('settings');
          },
        }
      : null,
    settingsViewProps: {
      requestJson,
      llm: llmSettingsState,
      deleteAction: deleteActionSettingsState,
      hubLogsState,
      hubLogsTailLines,
      hubLogsMaxBytes,
      activeTab: settingsActiveTab,
      focusedPlaybookId: settingsPlaybookFocusId,
      onBackToWorkspace: () => setAppView('workspace'),
      onSelectTab: (tabId) => setSettingsActiveTab(tabId),
      onFocusedPlaybookHandled: () => setSettingsPlaybookFocusId(null),
      onReplayOnboarding: () => {
        setAppView('workspace');
        onReplayOnboarding();
      },
      onResetOnboarding,
    },
    draftChatWorkspaceProps: draftChat
      ? {
          draftChat,
          createRuntime,
          onCreateRuntimeChange: setCreateRuntime,
          createAsDraft,
          onCreateAsDraftChange: setCreateAsDraft,
          createPersistVolume,
          onCreatePersistVolumeChange: setCreatePersistVolume,
          draftCreateMode,
          onDraftCreateModeChange: setDraftCreateMode,
          spawnAgentMenuEntries,
          draftCreating,
          draftAutoRenaming,
          spawnAgentConfig,
          createRepoMenuEntries,
          draftCreateRepoPath,
          repoBranchSource,
          onRepoBranchSourceChange: setRepoBranchSource,
          repoCreateRemoteBranch,
          onRepoCreateRemoteBranchChange: setRepoCreateRemoteBranch,
          draftRepoHostBranch: draftRepoBranchOptions?.hostBranch ?? null,
          draftRepoRemoteBranches: draftRepoBranchOptions?.remoteBranches ?? [],
          draftRepoBranchesLoading: draftRepoBranchOptions?.loading ?? false,
          draftRepoBranchesError: draftRepoBranchOptions?.error ?? null,
          draftCreateName,
          draftCreateGroup,
          draftCreateParentDroneLabel:
            drones.find(
              (drone: any) =>
                String(drone?.id ?? '').trim() === String(draftCreateParentDroneId ?? '').trim(),
            )?.name ??
            (String(draftCreateParentDroneId ?? '').trim() || null),
          draftCreateError,
          queuedPromptsByDroneChat,
          onCancel: () => {
            setDraftChat(null);
            setDraftCreateOpen(false);
            setDraftCreateError(null);
            setDraftCreateParentDroneId(null);
            setDraftAutoRenaming(false);
          },
          onStartDraftPrompt: startDraftPrompt,
          onStartDraftAutomation: startDraftAutomation,
          onQueueDraftPromptDuringCreate: queueDraftPromptDuringCreate,
          onEnqueueQueuedPrompt: enqueueQueuedPrompt,
          onDraftCreateGroupChange: setDraftCreateGroup,
          onDraftCreateNameChange: setDraftCreateName,
          onSetDraftCreateError: setDraftCreateError,
          onCreateEmptyDrone: () => createDroneFromDraft({ createMode: 'without-chat' }),
        }
      : null,
    playbookRunsWorkspaceProps: playbookRunsOpen
      ? {
          initialRepoPath: activeRepoPath,
          registeredRepoPaths,
          pullHostBranchBeforeCreate,
          onClose: () => setPlaybookRunsOpen(false),
          onOpenPlaybookSettings: (playbookId) => {
            setSettingsActiveTab('playbooks');
            setSettingsPlaybookFocusId(playbookId);
            setAppView('settings');
          },
          onDeleteRunDrone: (droneId) => {
            deleteDrone(droneId);
          },
          deletingDrones,
          optimisticallyDeletedDrones,
          onOpenRun: (droneId, chatName) => {
            setPlaybookRunsOpen(false);
            selectDroneChat(droneId, chatName);
          },
          onOpenArtifact: openPlaybookRunArtifact,
        }
      : null,
    groupMultiChatWorkspaceProps: selectedGroupMultiChatData
      ? {
          selectedGroupMultiChatData,
          groupBroadcastPromptError,
          groupBroadcastSending,
          onSendGroupBroadcastPrompt: sendGroupBroadcastPrompt,
          onAutoRenameChatFromFirstPrompt: handleAutoRenameChatFromFirstPrompt,
          uiDroneName,
          onSelectDroneCard: selectDroneCard,
          onDeleteDrone: deleteDrone,
          deletingDrones,
          onParseJobsFromAgentMessage: parseJobsFromAgentMessage,
          onSpawnDroneHubTaskFromAgentMessage: spawnDroneHubTaskFromAgentMessage,
        }
      : null,
    noDroneSelectedStateProps: {
      dronesLoading,
      sidebarDroneCount: sidebarDrones.length,
      dronesError,
      onOpenDraftChatComposer: openDraftChatComposer,
      onOpenCreateModal: openCreateModal,
      onOpenPlaybookRuns: openPlaybookRuns,
    },
    renderPersistentPreviewContent,
    selectedDroneWorkspaceProps: currentDrone
      ? {
          currentDrone,
          deleteMode,
          currentDroneLabel,
          showRespondingAsStatusInHeader,
          chatUiMode,
          loadingSession,
          sessionError,
          loadingTranscript,
          transcriptError,
          chatInfoError,
          loadingChatInfo,
          repoOpError,
          repoOpErrorMeta,
          openDroneErrorModal,
          launchHint,
          currentAgentKey,
          pickAgentValue,
          toolbarAgentMenuEntries,
          agentLocked,
          agentDisabled,
          agentLabel,
          chatRuntimeMetadataAvailable,
          modelControlEnabled,
          availableChatModels,
          currentModel,
          setChatModel,
          agentPermissionMode,
          setChatAgentPermissionMode,
          agentMessageAutoContinueEnabled,
          setAgentMessageAutoContinueEnabled,
          agentSuggestionEnabled,
          setAgentSuggestionEnabled,
          dockerSnapshotAfterAgentMessageEnabled,
          setDockerSnapshotAfterAgentMessageEnabled,
          setChatInfoError,
          modelMenuEntries,
          modelDisabled,
          modelLabel,
          manualChatModelInput,
          setManualChatModelInput,
          applyManualChatModel,
          setChatModelsRefreshNonce,
          loadingChatModels,
          chatModelsError,
          chatModelsDiscoveredAt,
          chatModelsSource,
          currentDroneRepoAttached,
          currentDroneRepoPath,
          createRepoMenuEntries,
          openDroneTerminal,
          openingTerminal,
          openDroneEditor,
          openingEditor,
          pullRepoChanges,
          pushRepoChanges,
          repoTransferPeers,
          pullRepoChangesFromDrone,
          applyRepoChangesToDrone,
          onRequestDropActions: openDroneDropActionModal,
          repoOp,
          headerOverflowRef,
          reseedRepo,
          terminalMenuRef,
          terminalLabel,
          terminalOptions,
          rightPanelOpen,
          setRightPanelOpen,
          requestRightPanelTab,
          rightPanelSplit,
          rightPanelTabs,
          rightPanelTab,
          setRightPanelTab,
          rightPanelTabLabels,
          transcripts,
          visiblePendingPromptsWithStartup,
          transcriptMessageId,
          parsingJobsByTurn,
          parseJobsFromAgentMessage,
          spawnDroneHubTaskFromAgentMessage,
          tldrByMessageId,
          showTldrByMessageId,
          toggleTldrForAgentMessage,
          handleAgentMessageHover,
          latestAgentSuggestionTarget,
          latestAgentSuggestionState,
          requestAgentSuggestionForMessage,
          chatEndRef,
          outputScrollRef,
          updatePinned,
          startupSeedForCurrentDrone,
          sessionText,
          pinnedToBottom,
          selectedDroneIdentity,
          promptError,
          sendingPrompt,
          sendPromptText,
          publishSelectedDraft,
          publishingDraft,
          canStopResponse,
          requestStopResponse,
          stoppingResponse,
          stopResponseError,
          requestCancelPendingPrompt,
          cancellingPendingPromptById,
          cancelPendingPromptErrorById,
          openedEditorFileOpenFailureMessage,
          openedEditorFileOpenFailureAt,
          onOpenMarkdownFileReference,
          rightPanelBottomTab,
          rightPanelOpenRequestSeq,
          renderRightPanelTabContent,
        }
      : null,
  };
}
