package com.huntelkator.voicestreamnext

object Constants {
    const val PREFS_NAME = "voice_stream_next_prefs"
    const val PREF_SERVER_URL = "server_url"
    const val PREF_AUTH_MODE = "auth_mode"
    const val PREF_BEARER_TOKEN = "bearer_token"
    const val PREF_DEV_EMAIL = "dev_email"
    const val PREF_DEV_NAME = "dev_name"
    const val PREF_DEV_ADMIN = "dev_admin"
    const val PREF_DEVICE_ID = "device_id"
    const val PREF_DEVICE_TOKEN = "device_token"
    const val PREF_DEVICE_NAME = "device_name"
    const val PREF_INSTALLATION_ID = "installation_id"
    const val PREF_ANDROID_ECHO_CANCELLATION = "android_echo_cancellation"
    const val PREF_SUPPRESS_WAKE_DURING_PLAYBACK = "suppress_wake_during_playback"
    const val PREF_MICROPHONE_DEVICE_KEY = "microphone_device_key"

    const val ACTION_START_VOICE = "com.huntelkator.voicestreamnext.action.START_VOICE"
    const val ACTION_START_AWAKE = "com.huntelkator.voicestreamnext.action.START_AWAKE"
    const val ACTION_SLEEP = "com.huntelkator.voicestreamnext.action.SLEEP"
    const val ACTION_STOP_RECORDING = "com.huntelkator.voicestreamnext.action.STOP_RECORDING"
    const val ACTION_STOP_VOICE = "com.huntelkator.voicestreamnext.action.STOP_VOICE"
    const val ACTION_QUERY_STATUS = "com.huntelkator.voicestreamnext.action.QUERY_STATUS"
    const val ACTION_SET_MICROPHONE = "com.huntelkator.voicestreamnext.action.SET_MICROPHONE"
    const val ACTION_STATUS = "com.huntelkator.voicestreamnext.action.STATUS"
    const val ACTION_SPEECH_HISTORY_CHANGED = "com.huntelkator.voicestreamnext.action.SPEECH_HISTORY_CHANGED"
    const val ACTION_ANDROID_UPDATE_AVAILABLE = "com.huntelkator.voicestreamnext.action.ANDROID_UPDATE_AVAILABLE"

    const val EXTRA_STATUS = "status"
    const val EXTRA_MODE = "mode"
    const val EXTRA_MICROPHONE = "microphone"
    const val EXTRA_MICROPHONE_DEVICE_KEY = "microphone_device_key"
    const val EXTRA_APPROVAL_STATUS = "approval_status"
    const val EXTRA_STREAM_TARGET = "stream_target"
    const val EXTRA_UPDATE_VERSION_CODE = "update_version_code"
    const val EXTRA_UPDATE_APK_URL = "update_apk_url"

    const val MODE_OFF = "off"
    const val MODE_LOADING = "loading"
    const val MODE_AWAKE = "awake"
    const val MODE_SLEEPING = "sleeping"
    const val MODE_RECORDING = "recording"
    const val MODE_ERROR = "error"

    const val AUTH_DEV = "dev"
    const val AUTH_BEARER = "bearer"
    const val STREAM_TARGET_ASSISTANT = "assistant"
    const val STREAM_TARGET_PATCH = "patch"
    const val STREAM_TARGET_CLIPBOARD = "clipboard"
    val DEFAULT_SERVER_URL = BuildConfig.DEFAULT_SERVER_URL
    const val DEFAULT_DEV_EMAIL = "android@example.local"
    const val DEFAULT_DEV_NAME = "Android Operator"
    const val DEFAULT_DEVICE_NAME = "Android voice client"
}
