import { RepositoryOperationService } from '../repository-operation-route-service';
import type { LegacyRouteDependencyContract, LegacyRouteHandler } from './legacy-route';

type RepositoryDependencyName =
  | 'GITHUB_PULL_REQUEST_LIST_CACHE_TTL_MS'
  | 'PULL_PREVIEW_HOST_MERGE_CACHE_TTL_MS'
  | 'applyBranchMergeNoCommitToMainWorkingTree'
  | 'attachReviewMetadataToPullEntries'
  | 'buildReviewScopeId'
  | 'clearGithubPullRequestListCache'
  | 'closeGithubPullRequestForRepoRoot'
  | 'commitDroneMetadataPatch'
  | 'createHostAuthoredMirrorCommit'
  | 'defaultRepoSeedTimeoutMs'
  | 'deleteHostRefBestEffort'
  | 'droneRepoBaseSha'
  | 'droneRepoChangesSummary'
  | 'droneRepoCommitDetails'
  | 'droneRepoCommitDiffForPath'
  | 'droneRepoCommitList'
  | 'droneRepoDiffForPath'
  | 'droneRepoPathInContainer'
  | 'droneRepoPullChangesSummary'
  | 'droneRepoPullDiffForPath'
  | 'droneRootPath'
  | 'droneRuntime'
  | 'droneUnmergedFiles'
  | 'dvmExec'
  | 'dvmRepoExport'
  | 'dvmRepoHeadSha'
  | 'dvmRepoSeed'
  | 'dvmRepoSetBaseSha'
  | 'exportFullHeadBundleFromDrone'
  | 'findDroneIdByRef'
  | 'getGithubPullRequestCommitForRepoRoot'
  | 'gitCurrentBranchOrSha'
  | 'gitIsAncestor'
  | 'gitIsClean'
  | 'gitMergeBase'
  | 'gitMergePreviewNameStatusEntries'
  | 'gitRepoChangesSummary'
  | 'gitRepoCommitDetails'
  | 'gitRepoCommitDiffForPath'
  | 'gitRepoCommitList'
  | 'gitRepoDiffForPath'
  | 'gitResolveCommitSha'
  | 'gitTopLevel'
  | 'githubPullRequestListCache'
  | 'hubLog'
  | 'importBundleHeadToDroneRef'
  | 'importBundleHeadToHostRef'
  | 'inspectGithubRepoForRepoRoot'
  | 'isGithubPullRequestError'
  | 'isRepoAttachedDrone'
  | 'isRepoPatchApplyError'
  | 'listGithubPullRequestChangesForRepoRoot'
  | 'listGithubPullRequestCommitsForRepoRoot'
  | 'listGithubPullRequestsForRepoRoot'
  | 'loadRegistry'
  | 'looksLikeBundleMissingPrerequisiteError'
  | 'looksLikeEmptyBundleExportError'
  | 'looksLikeMissingContainerError'
  | 'looksLikeRepoUnavailableError'
  | 'looksLikeUnrelatedHistoriesError'
  | 'mergeGithubPullRequestForRepoRoot'
  | 'nameStatusCharToType'
  | 'normalizeGithubPullRequestListState'
  | 'normalizeGithubPullRequestMergeMethod'
  | 'nowIso'
  | 'parseMergeConflictFilesFromText'
  | 'parseShaFromText'
  | 'pullPreviewHostMergeCache'
  | 'reconcilePendingHostMirrorApply'
  | 'repoBaseRefMatchesCurrentHostBranch'
  | 'repoChangesScanCache'
  | 'resolveDroneOrRespond'
  | 'resolveLanguageDefinition'
  | 'resolveLanguageReferences'
  | 'runGitInDrone'
  | 'runGitInDroneOrThrow'
  | 'runHostCommand'
  | 'safeDroneRefSegment'
  | 'setDroneHubMetaByIdentity'
  | 'syncRepoAgentsInstructionsForDrone'
  | 'updateHostRef'
  | 'withLockedDroneContainer'
  | 'withLockedDroneContainers'
  | 'withReadonlyDroneContainer';

export type RepositoryRouteDependencies = LegacyRouteDependencyContract<RepositoryDependencyName>;

export function createRepositoryRouteHandler(
  deps: RepositoryRouteDependencies,
): LegacyRouteHandler {
  return new RepositoryOperationService(deps).handle;
}
